version: '3.8'
services:
  app:
    build:
      context: ./Docker/application
      dockerfile: Dockerfile
    container_name: symfony
    working_dir: /App
    volumes:
      - ./application:/App
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - 8000:80
    volumes:
      - ./application:/App
      - ./Docker/Nginx:/etc/nginx/conf.d
  mongodb:
    build: ./Docker/Database
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - ./Docker/Database/data:/data/db:rw
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
